In [2]:
import torch

In [7]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y,x%y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]),
 tensor([1., 0., 0., 0.]))

In [8]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [10]:
x=torch.arange(12,dtype=torch.float32).reshape((3,4))
print(x)
y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
print(y)
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)  # dim=0表示列数不变，=1表示行数不变

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [11]:
x==y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [12]:
x.sum()  # 对x中所有元素求和，得出标量

tensor(66.)

In [13]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [14]:
a+b  # 广播机制，a和b都变成了3x2的矩阵

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [16]:
x=torch.arange(12,dtype=torch.float32).reshape((3,4))
x[-1],x[1:3]  # 前一个表示输出倒数第一行，后一个表示输出第一第二行（存在第0行）

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [17]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [18]:
x[1,2]=100
x

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5., 100.,   7.],
        [  8.,   9.,  10.,  11.]])

In [20]:
x[0:2,:]=24
x

tensor([[24., 24., 24., 24.],
        [24., 24., 24., 24.],
        [ 8.,  9., 10., 11.]])

In [21]:
before=id(y)
y=y+x
id(y)==before  # 此操作导致为新的结果分配内存

False

In [23]:
z=torch.zeros_like(y)
print('id(z):',id(z))
z[:]=x+y
print('id(z):',id(z))  # 原地操作

id(z): 6115117968
id(z): 6115117968


In [24]:
before=id(x)
x+=y
id(x)==before  # 可以使用上一行和这一行的操作来减少内存的开销 注意过多复制的情况

True

In [25]:
A=x.numpy()
B=torch.tensor(A)  # 转换numpy张量
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [27]:
a=torch.tensor([3.4])
a,a.item(),float(a),int(a)

(tensor([3.4000]), 3.4000000953674316, 3.4000000953674316, 3)