In [18]:
import torch

In [19]:
x=torch.arange(12)
x  #在 Python中相当于print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
x.shape  # 访问张量的形状和其中元素的个数

torch.Size([12])

In [21]:
x.numel()

12

In [22]:
x=x.reshape(3,4)  # reshape改变张量的形状而不改变张量的元素数量
x 

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [23]:
torch.zeros((2,3,4))  # 两个二维向量，二维向量为三行四列

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [24]:
torch.ones((3,3,5))

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [27]:
y=torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]])
print(y)

tensor([[[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]])


In [28]:
y.shape

torch.Size([1, 3, 4])

In [29]:
torch.exp(y)

tensor([[[ 7.3891,  2.7183, 54.5982, 20.0855],
         [ 2.7183,  7.3891, 20.0855, 54.5982],
         [54.5982, 20.0855,  7.3891,  2.7183]]])