In [2]:
import torch
x=torch.tensor([3.0])
y=torch.tensor([2.0])  # 标量

x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [3]:
x=torch.arange(4)  # 向量可以看作是标量值组成的列表
x

tensor([0, 1, 2, 3])

In [4]:
x[3]  # 通过索引值来进行访问

tensor(3)

In [5]:
len(x)

4

In [6]:
x.shape  # 表示x为一行四列

torch.Size([4])

In [7]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
A.T  # 矩阵的转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [9]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B  # 对称矩阵

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [10]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [11]:
X=torch.arange(24).reshape(2,3,4)  # 两个3X4的矩阵
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [12]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()  # 通过分配新的内存，将A的一个副本分配给B
A,B,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [13]:
A*B  # 两个矩阵按元素相乘，此种方式被称为哈达玛积

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [14]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X,a*X,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]))

In [15]:
x=torch.arange(4,dtype=torch.float32)
x.sum(),x

(tensor(6.), tensor([0., 1., 2., 3.]))

In [16]:
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190.))

In [17]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [18]:
A_sum_axis0=A.sum(axis=0)  # 对所有的行元素进行求和来降维，得出一行四列的张量
A_sum_axis0,A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [19]:
A_sum_axis1=A.sum(axis=1)  # 对所有的列元素进行求和来降维，得出一行五列的张量
A_sum_axis1,A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [20]:
A.sum(axis=[0,1])  # 沿着行和列对矩阵求和，等价于对矩阵所有元素进行求和，与A.sum的结果相同

tensor(190.)

In [21]:
A.mean(),A.sum()/A.numel()  # 平均值是指元素总和除以元素个数


(tensor(9.5000), tensor(9.5000))

In [22]:
A.numel()

20

In [23]:
A.mean(axis=0),A.sum(axis=0)/A.shape[0]  # 计算指定轴的平均值

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [24]:
A.mean(axis=1),A.sum(axis=1)/A.shape[1]

(tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000]),
 tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000]))

In [25]:
print('矩阵A的行数为：',A.shape[0])
print('矩阵A的列数为：',A.shape[1])

矩阵A的行数为： 5
矩阵A的列数为： 4


In [26]:
sum_A=A.sum(axis=0,keepdim=True)
sum_A

tensor([[40., 45., 50., 55.]])

In [27]:
sum_A=A.sum(axis=1,keepdim=True)  # 保持轴数不变，列元素求和之后保持五行一列
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [28]:
A/sum_A  # 利用广播机制进行相除

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [29]:
A.cumsum(axis=0)
# 按行计算，第二行=原来第二行+第一行，第三行=原来第三行+第二行（不是原来的第二行）

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [30]:
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y) # 求点积，得出一个标量

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [31]:
torch.sum(x*y)  # 这种方法也可以进行求点积的运算

tensor(6.)

In [32]:
A.shape,x.shape,torch.mv(A,x)  # 使用张量表示矩阵-向量积

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [33]:
B=torch.ones(4,3)
A,B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

In [34]:
torch.mm(A,B)  # 矩阵乘法

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [35]:
u=torch.tensor([3.0,-4])
torch.norm(u)  # 计算向量的L2范数，L2范数为向量元素平方和的平方根

tensor(5.)

In [36]:
torch.abs(u).sum()  # 计算L1范数，L1范数为向量元素的绝对值之和

tensor(7.)

In [38]:
# 弗罗贝尔乌斯范数为矩阵元素平方和的平方根，类似于矩阵型向量的L2范数
torch.norm(torch.ones((4,9)))

tensor(6.)